# General
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_TITLE = "Neododge"

# HUD
HUD_FONT = "kenney_pixel.ttf"
HUD_FONT_SIZE = 16
WAVE_TEXT_DURATION = 120  # frames
PICKUP_TEXT_FADE_RATE = 3
HUD_MARGIN = 20
COOLDOWN_BAR_WIDTH = 100
COOLDOWN_BAR_HEIGHT = 10

# Player
PLAYER_SCALE = 0.035
PLAYER_SPEED = 250
PLAYER_DASH_DISTANCE = 150
PLAYER_DASH_COOLDOWN = 1.0
PLAYER_DASH_SPEED = 1000
PLAYER_MOVE_SPEED = 5

# Game constants
MAX_HEARTS = 3
INVINCIBILITY_TIME = 1.0

# Wave settings
WAVE_DURATION = 30  # seconds per wave

# UI Layout
HEALTH_X_OFFSET = 20
HEALTH_Y_OFFSET = 550
COIN_TEXT_POS = (700, 20)

# Artifact settings
ARTIFACT_SCALE = 0.035

# Asset paths
SKINS_DIR = "assets/skins"
DEFAULT_SKIN_PATH = "assets/skins/default"
MDMA_SKIN_PATH = "assets/skins/mdma"
